api:
  model: ''
  prompt_text: 请将图中的英文翻译成中文后以中文回复文本，如果包含数学公式请用tex格式输出。
  api_key: ''
  base_url: ''
  proxy: ''
app_settings:
  screenshot_hotkey: ctrl+alt+s
  initial_font_size: 24
  max_windows: 0
  zoom_sensitivity: 500
  debug_mode: false
